project:
  type: default
  render:
    - main.qmd

execute:
  freeze: auto

bibliography: references/references.bib
csl: references/apa.csl
cite-method: citeproc
output-file: WCPFC-SC22-2026-SA-WP-06.pdf

filters:
  - inline-code.lua
  - page-breaks.lua

format:
  pdf:
    documentclass: SCreport
    classoption: [a4paper, 11pt]
    papersize: a4
    include-in-header:
      - styles/wcpfc-sc22.tex
    include-before-body:
      - styles/revision.tex
    pdf-engine: pdflatex
    latex-auto-install: true
    keep-tex: true
    toc: true
    number-sections: true
    geometry:
      - margin=1in
    fig-pos: H
    colorlinks: true
    linkcolor: SCblue
    urlcolor: SCblue
    citecolor: SCblue
