`%||%` <- function(x, y) if (is.null(x) || length(x) == 0) y else x

read_report_csv <- function(path) {
  if (!file.exists(path)) {
    return(data.frame(stringsAsFactors = FALSE))
  }
  utils::read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
}

bind_report_rows <- function(rows) {
  rows <- rows[vapply(rows, function(x) is.data.frame(x) && nrow(x), logical(1))]
  if (!length(rows)) {
    return(data.frame(stringsAsFactors = FALSE))
  }
  cols <- unique(unlist(lapply(rows, names), use.names = FALSE))
  rows <- lapply(rows, function(x) {
    missing <- setdiff(cols, names(x))
    for (name in missing) x[[name]] <- NA
    x[, cols, drop = FALSE]
  })
  do.call(rbind, rows)
}

is_internal_report_table <- function(path) {
  base <- tolower(basename(path))
  grepl(
    paste(
      "^(payload-index(-[0-9]+)?|model-index|plot-summary|report-files|",
      "report-input-.*|report-prep-summary|figure-index|table-index|",
      "generated-table-index|figure-optimization|mfclshiny-.*|",
      ".*build-log.*|.*report-summary)[.]csv$",
      sep = ""
    ),
    base
  )
}

split_catalog_paths <- function(x) {
  x <- as.character(x %||% "")
  x <- unlist(strsplit(x, ";", fixed = TRUE), use.names = FALSE)
  x <- trimws(x)
  x[nzchar(x)]
}

slug_id <- function(x) {
  x <- tolower(as.character(x %||% "item"))
  x <- gsub("[^a-z0-9]+", "-", x)
  x <- gsub("(^-+|-+$)", "", x)
  if (!nzchar(x)) "item" else x
}

clean_text <- function(x) {
  x <- trimws(as.character(x %||% ""))
  x[is.na(x)] <- ""
  x
}

has_text <- function(x) {
  any(nzchar(clean_text(x)))
}

file_match_tokens <- function(path) {
  path <- as.character(path %||% "")
  base <- tolower(basename(path))
  stem <- tolower(tools::file_path_sans_ext(base))
  unique(c(base, stem, slug_id(stem)))
}

is_optimized_sidecar_figure <- function(path) {
  path <- as.character(path %||% "")
  ext <- tolower(tools::file_ext(path))
  sidecar <- ext %in% c("webp", "jpg", "jpeg")
  base_png <- sub("[.](webp|jpe?g)$", ".png", path, ignore.case = TRUE)
  sidecar & file.exists(base_png)
}

preferred_figure_file <- function(file) {
  file <- as.character(file %||% "")
  if (!nzchar(file) || !file.exists(file)) {
    return(file)
  }
  stem <- sub("[.][^.]+$", "", file)
  if (requireNamespace("knitr", quietly = TRUE) &&
      isTRUE(knitr::is_html_output()) &&
      isTRUE(get0("use_webp_figures", ifnotfound = TRUE))) {
    candidate <- paste0(stem, ".webp")
    if (file.exists(candidate)) {
      return(candidate)
    }
  }
  if (requireNamespace("knitr", quietly = TRUE) &&
      isTRUE(knitr::is_latex_output()) &&
      isTRUE(get0("use_pdf_jpeg_figures", ifnotfound = TRUE))) {
    for (ext in c(".jpg", ".jpeg")) {
      candidate <- paste0(stem, ext)
      if (file.exists(candidate)) {
        return(candidate)
      }
    }
  }
  file
}

catalog_candidate_tokens <- function(candidates) {
  candidates <- split_catalog_paths(candidates)
  unique(unlist(lapply(candidates, file_match_tokens), use.names = FALSE))
}

render_report_text <- function(x) {
  x <- as.character(x %||% "")
  values <- list(
    species = get0("species_code", ifnotfound = "TUNA"),
    species_code = get0("species_code", ifnotfound = "TUNA"),
    species_label = get0("species_label", ifnotfound = "selected tuna stock"),
    species_scientific = get0("species_scientific", ifnotfound = "Thunnus spp."),
    assessment_year = get0("assessment_year", ifnotfound = format(Sys.Date(), "%Y")),
    assessment_area = get0("assessment_area", ifnotfound = "the WCPO"),
    previous_assessment_year = get0("previous_assessment_year", ifnotfound = "the previous assessment"),
    model_region_count = get0("model_region_count", ifnotfound = "TODO"),
    latest_data_year = get0("latest_data_year", ifnotfound = "TODO"),
    recent_period = get0("recent_period", ifnotfound = "TODO"),
    no_fishing_reference_period = get0("no_fishing_reference_period", ifnotfound = "TODO")
  )
  for (name in names(values)) {
    x <- gsub(paste0("{", name, "}"), as.character(values[[name]]), x, fixed = TRUE)
  }
  x
}

polish_report_caption <- function(x) {
  x <- render_report_text(x)
  x <- gsub("\\s+", " ", x)
  replacements <- c(
    "generated from the current mfclshiny app state" = "prepared from the current assessment plotting state",
    "Generated from the current mfclshiny app state" = "Prepared from the current assessment plotting state",
    "generated by mfclshiny for report use and is the same figure bundle that can be opened in the mfclshiny Report Figures tab" = "prepared for report use",
    "model outputs" = "assessment results",
    "selected model scenarios" = "selected assessment models",
    "selected scenarios" = "selected assessment models",
    "model scenarios" = "assessment models",
    "plotted outputs" = "plotted quantities"
  )
  for (from in names(replacements)) {
    x <- gsub(from, replacements[[from]], x, fixed = TRUE)
  }
  x <- gsub(
    "\\s+(for|in|from|of|used in) the [0-9]{4}\\s+bigeye tuna\\s*(\\(BET\\))?\\s+assessment\\b",
    "",
    x,
    ignore.case = TRUE,
    perl = TRUE
  )
  x <- gsub(
    "^the [0-9]{4}\\s+bigeye tuna\\s*(\\(BET\\))?\\s+assessment\\s+",
    "",
    x,
    ignore.case = TRUE,
    perl = TRUE
  )
  x <- gsub(
    "\\bthe [0-9]{4}\\s+bigeye tuna\\s*(\\(BET\\))?\\s+assessment\\b",
    "",
    x,
    ignore.case = TRUE,
    perl = TRUE
  )
  x <- gsub("\\b(for|in) the ([0-9]{4} [^.,;]+?) assessment results\\b", "\\1 the \\2 assessment", x, perl = TRUE)
  x <- gsub("\\bthe ([0-9]{4} [^.,;]+?) assessment results\\b", "the \\1 assessment", x, perl = TRUE)
  x <- gsub("\\s+([.,;:])", "\\1", x, perl = TRUE)
  x <- trimws(gsub("\\s+", " ", x))
  ifelse(nzchar(x), paste0(toupper(substr(x, 1, 1)), substr(x, 2, nchar(x))), x)
}

latex_escape <- function(x) {
  x <- as.character(x %||% "")
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x)
  x
}

html_escape <- function(x) {
  x <- as.character(x %||% "")
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub("\"", "&quot;", x, fixed = TRUE)
  x <- gsub("'", "&#39;", x, fixed = TRUE)
  x
}

markdown_path <- function(path) {
  gsub(" ", "%20", gsub("\\\\", "/", path))
}

report_paths <- function(name, default = character()) {
  value <- get0(name, ifnotfound = paste(default, collapse = ";"))
  out <- split_catalog_paths(value)
  if (!length(out)) default else out
}

find_report_assets <- function(candidates, roots = c("Figures")) {
  candidates <- split_catalog_paths(candidates)
  if (!length(candidates)) {
    return(character())
  }

  found <- candidates[file.exists(candidates)]

  roots <- roots[dir.exists(roots)]
  for (root in roots) {
    direct <- file.path(root, candidates)
    found <- c(found, direct[file.exists(direct)])
  }

  all_files <- unique(unlist(lapply(roots, function(root) {
    list.files(root, recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
  }), use.names = FALSE))
  all_files <- all_files[!is_optimized_sidecar_figure(all_files)]
  if (length(all_files)) {
    all_base <- tolower(basename(all_files))
    candidate_base <- tolower(basename(candidates))
    hit <- match(candidate_base, all_base, nomatch = 0L)
    if (any(hit > 0L)) {
      found <- c(found, all_files[hit[hit > 0L]])
    }

    candidate_stems <- tools::file_path_sans_ext(candidate_base)
    all_stems <- tools::file_path_sans_ext(all_base)
    hit <- match(candidate_stems, all_stems, nomatch = 0L)
    if (any(hit > 0L)) {
      found <- c(found, all_files[hit[hit > 0L]])
    }
  }

  unique(found)
}

find_report_asset <- function(candidates, roots = c("Figures")) {
  assets <- find_report_assets(candidates, roots = roots)
  if (length(assets)) assets[[1]] else ""
}

read_figure_metadata <- function(roots = c("Figures")) {
  roots <- roots[dir.exists(roots)]
  files <- unique(unlist(lapply(roots, function(root) {
    list.files(root, pattern = "figure-index[.]csv$|mfclshiny-figure-index[.]csv$", recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
  }), use.names = FALSE))
  if (!length(files)) {
    return(data.frame(stringsAsFactors = FALSE))
  }
  rows <- lapply(files, function(file) {
    x <- read_report_csv(file)
    if (!nrow(x)) {
      return(x)
    }
    x$metadata_file <- file
    x
  })
  out <- bind_report_rows(rows)
  if (is.null(out) || !nrow(out)) {
    return(data.frame(stringsAsFactors = FALSE))
  }
  out
}

figure_metadata_row <- function(file, metadata) {
  if (is.null(metadata) || !nrow(metadata)) {
    return(NULL)
  }
  file_base <- tolower(basename(file))
  candidates <- character()
  for (name in intersect(c("file", "relative_path"), names(metadata))) {
    candidates <- c(candidates, tolower(basename(metadata[[name]])))
  }
  hit <- match(file_base, candidates, nomatch = 0L)
  if (!hit) {
    return(NULL)
  }
  source_col <- rep(seq_len(nrow(metadata)), length(intersect(c("file", "relative_path"), names(metadata))))
  metadata[source_col[[hit]], , drop = FALSE]
}

figure_caption <- function(file, default, metadata = data.frame(), override = "") {
  override <- render_report_text(override)
  if (nzchar(trimws(override))) {
    return(polish_report_caption(override))
  }
  row <- figure_metadata_row(file, metadata)
  if (!is.null(row) && "caption" %in% names(row)) {
    caption <- render_report_text(row$caption[[1]])
    if (nzchar(trimws(caption))) {
      return(polish_report_caption(caption))
    }
  }
  polish_report_caption(default)
}

normalize_figure_placement <- function(x, default = "main") {
  value <- tolower(trimws(as.character(x %||% "")))
  if (!nzchar(value) || is.na(value)) {
    value <- default
  }
  value <- gsub("[^a-z0-9]+", "-", value)
  aliases <- c(
    body = "main",
    report = "main",
    primary = "main",
    include = "main",
    yes = "main",
    y = "main",
    true = "main",
    "1" = "main",
    supplemental = "appendix",
    supplement = "appendix",
    supp = "appendix",
    extra = "appendix",
    excluded = "exclude",
    skip = "exclude",
    omit = "exclude",
    no = "exclude",
    n = "exclude",
    false = "exclude",
    "0" = "exclude"
  )
  if (value %in% names(aliases)) {
    value <- aliases[[value]]
  }
  if (value %in% c("main", "appendix", "exclude")) value else default
}

catalog_figure_placement <- function(catalog, default = "main") {
  catalog <- complete_catalog(catalog, "figures")
  vapply(catalog$placement, normalize_figure_placement, character(1), default = default)
}

complete_figure_curation <- function(curation) {
  needed <- c("target_type", "target", "placement", "section", "title", "caption_override", "order", "notes")
  if (!is.data.frame(curation)) {
    curation <- data.frame(stringsAsFactors = FALSE)
  }
  if (!nrow(curation)) {
    out <- as.data.frame(stats::setNames(rep(list(character()), length(needed)), needed), stringsAsFactors = FALSE)
    return(out[, needed, drop = FALSE])
  }
  for (name in setdiff(needed, names(curation))) {
    curation[[name]] <- ""
  }
  curation[, needed, drop = FALSE]
}

figure_curation_target_type <- function(x) {
  value <- tolower(clean_text(x))
  value <- gsub("[^a-z0-9]+", "-", value)
  value[value %in% c("", "catalog", "catalog-key", "row")] <- "key"
  value[value %in% c("filename", "path", "image")] <- "file"
  value[!value %in% c("key", "file")] <- "key"
  value
}

figure_curation_matches_key <- function(curation, key, candidates = "") {
  curation <- complete_figure_curation(curation)
  if (!nrow(curation)) {
    return(curation[0, , drop = FALSE])
  }
  target_type <- figure_curation_target_type(curation$target_type)
  targets <- clean_text(curation$target)
  key_tokens <- unique(c(tolower(clean_text(key)), slug_id(key)))
  target_slugs <- vapply(targets, slug_id, character(1))
  hit <- target_type == "key" & (tolower(targets) %in% key_tokens | target_slugs %in% key_tokens)
  curation[hit & nzchar(targets), , drop = FALSE]
}

figure_curation_matches_file <- function(curation, file) {
  curation <- complete_figure_curation(curation)
  if (!nrow(curation)) {
    return(curation[0, , drop = FALSE])
  }
  target_type <- figure_curation_target_type(curation$target_type)
  targets <- clean_text(curation$target)
  file_tokens <- file_match_tokens(file)
  target_stem_slugs <- vapply(tools::file_path_sans_ext(targets), slug_id, character(1))
  hit <- target_type == "file" &
    (tolower(basename(targets)) %in% file_tokens | target_stem_slugs %in% file_tokens)
  curation[hit & nzchar(targets), , drop = FALSE]
}

last_nonempty <- function(x) {
  x <- clean_text(x)
  x <- x[nzchar(x)]
  if (length(x)) x[[length(x)]] else ""
}

apply_figure_curation <- function(catalog, curation = data.frame()) {
  catalog <- complete_catalog(catalog, "figures")
  curation <- complete_figure_curation(curation)
  if (!nrow(catalog) || !nrow(curation)) {
    return(catalog)
  }
  catalog$.original_order <- seq_len(nrow(catalog))
  catalog$.curation_order <- NA_real_
  for (i in seq_len(nrow(catalog))) {
    matches <- figure_curation_matches_key(
      curation,
      key = catalog$key[[i]],
      candidates = catalog$file_candidates[[i]]
    )
    if (!nrow(matches)) {
      next
    }
    for (field in c("placement", "section", "title", "caption_override", "notes")) {
      value <- last_nonempty(matches[[field]])
      if (nzchar(value)) {
        catalog[[field]][[i]] <- value
      }
    }
    order_value <- suppressWarnings(as.numeric(last_nonempty(matches$order)))
    if (is.finite(order_value)) {
      catalog$.curation_order[[i]] <- order_value
    }
  }
  if (any(is.finite(catalog$.curation_order))) {
    catalog <- catalog[order(is.na(catalog$.curation_order), catalog$.curation_order, catalog$.original_order), , drop = FALSE]
  }
  catalog$.original_order <- NULL
  catalog$.curation_order <- NULL
  rownames(catalog) <- NULL
  catalog
}

filter_catalog_figures <- function(catalog, placements = "main") {
  if (!nrow(catalog)) {
    return(complete_catalog(catalog, "figures"))
  }
  catalog <- complete_catalog(catalog, "figures")
  wanted <- vapply(placements, normalize_figure_placement, character(1), default = "main")
  catalog[catalog_figure_placement(catalog) %in% wanted, , drop = FALSE]
}

complete_table_curation <- function(curation) {
  needed <- c("target_type", "target", "placement", "section", "title", "caption_override", "order", "notes")
  if (!is.data.frame(curation)) {
    curation <- data.frame(stringsAsFactors = FALSE)
  }
  if (!nrow(curation)) {
    out <- as.data.frame(stats::setNames(rep(list(character()), length(needed)), needed), stringsAsFactors = FALSE)
    return(out[, needed, drop = FALSE])
  }
  for (name in setdiff(needed, names(curation))) {
    curation[[name]] <- ""
  }
  curation[, needed, drop = FALSE]
}

table_curation_target_type <- function(x) {
  value <- tolower(clean_text(x))
  value <- gsub("[^a-z0-9]+", "-", value)
  value[value %in% c("", "catalog", "catalog-key", "row")] <- "key"
  value[value %in% c("filename", "path", "csv")] <- "file"
  value[!value %in% c("key", "file")] <- "key"
  value
}

table_curation_matches_key <- function(curation, key, candidates = "") {
  curation <- complete_table_curation(curation)
  if (!nrow(curation)) {
    return(curation[0, , drop = FALSE])
  }
  target_type <- table_curation_target_type(curation$target_type)
  targets <- clean_text(curation$target)
  key_tokens <- unique(c(tolower(clean_text(key)), slug_id(key)))
  target_slugs <- vapply(targets, slug_id, character(1))
  hit <- target_type == "key" & (tolower(targets) %in% key_tokens | target_slugs %in% key_tokens)
  curation[hit & nzchar(targets), , drop = FALSE]
}

table_curation_matches_file <- function(curation, file) {
  curation <- complete_table_curation(curation)
  if (!nrow(curation)) {
    return(curation[0, , drop = FALSE])
  }
  target_type <- table_curation_target_type(curation$target_type)
  targets <- clean_text(curation$target)
  file_tokens <- file_match_tokens(file)
  target_stem_slugs <- vapply(tools::file_path_sans_ext(targets), slug_id, character(1))
  hit <- target_type == "file" &
    (tolower(basename(targets)) %in% file_tokens | target_stem_slugs %in% file_tokens)
  curation[hit & nzchar(targets), , drop = FALSE]
}

apply_table_curation <- function(catalog, curation = data.frame()) {
  catalog <- complete_catalog(catalog, "tables")
  curation <- complete_table_curation(curation)
  if (!nrow(catalog) || !nrow(curation)) {
    return(catalog)
  }
  catalog$.original_order <- seq_len(nrow(catalog))
  catalog$.curation_order <- NA_real_
  for (i in seq_len(nrow(catalog))) {
    matches <- table_curation_matches_key(
      curation,
      key = catalog$key[[i]],
      candidates = catalog$file_candidates[[i]]
    )
    if (!nrow(matches)) {
      next
    }
    for (field in c("placement", "section", "title", "caption_override", "notes")) {
      value <- last_nonempty(matches[[field]])
      if (nzchar(value)) {
        catalog[[field]][[i]] <- value
      }
    }
    order_value <- suppressWarnings(as.numeric(last_nonempty(matches$order)))
    if (is.finite(order_value)) {
      catalog$.curation_order[[i]] <- order_value
    }
  }
  if (any(is.finite(catalog$.curation_order))) {
    catalog <- catalog[order(is.na(catalog$.curation_order), catalog$.curation_order, catalog$.original_order), , drop = FALSE]
  }
  catalog$.original_order <- NULL
  catalog$.curation_order <- NULL
  rownames(catalog) <- NULL
  catalog
}

catalog_table_placement <- function(catalog, default = "main") {
  catalog <- complete_catalog(catalog, "tables")
  vapply(catalog$placement, normalize_figure_placement, character(1), default = default)
}

filter_catalog_tables <- function(catalog, placements = "main") {
  if (!nrow(catalog)) {
    return(complete_catalog(catalog, "tables"))
  }
  catalog <- complete_catalog(catalog, "tables")
  wanted <- vapply(placements, normalize_figure_placement, character(1), default = "main")
  catalog[catalog_table_placement(catalog) %in% wanted, , drop = FALSE]
}

read_table_metadata <- function(roots = c("tables")) {
  roots <- roots[dir.exists(roots)]
  files <- unique(unlist(lapply(roots, function(root) {
    list.files(
      root,
      pattern = "table-index[.]csv$|mfclshiny-table-index[.]csv$|generated-table-index[.]csv$",
      recursive = TRUE,
      full.names = TRUE,
      ignore.case = TRUE
    )
  }), use.names = FALSE))
  if (!length(files)) {
    return(data.frame(stringsAsFactors = FALSE))
  }
  rows <- lapply(files, function(file) {
    x <- read_report_csv(file)
    if (!nrow(x)) {
      return(x)
    }
    x$metadata_file <- file
    x
  })
  out <- bind_report_rows(rows)
  if (is.null(out) || !nrow(out)) {
    return(data.frame(stringsAsFactors = FALSE))
  }
  out
}

table_metadata_row <- function(file, metadata) {
  if (is.null(metadata) || !nrow(metadata)) {
    return(NULL)
  }
  file_base <- tolower(basename(file))
  candidates <- character()
  source_rows <- integer()
  for (name in intersect(c("file", "relative_path"), names(metadata))) {
    values <- tolower(basename(metadata[[name]]))
    candidates <- c(candidates, values)
    source_rows <- c(source_rows, seq_len(nrow(metadata)))
  }
  hit <- match(file_base, candidates, nomatch = 0L)
  if (!hit) {
    return(NULL)
  }
  metadata[source_rows[[hit]], , drop = FALSE]
}

table_caption <- function(file, default, metadata = data.frame(), override = "") {
  override <- render_report_text(override)
  if (nzchar(trimws(override))) {
    return(polish_report_caption(override))
  }
  row <- table_metadata_row(file, metadata)
  if (!is.null(row) && "caption" %in% names(row)) {
    caption <- render_report_text(row$caption[[1]])
    if (nzchar(trimws(caption))) {
      return(polish_report_caption(caption))
    }
  }
  polish_report_caption(default)
}

prepare_report_table <- function(x,
                                 max_rows = 30,
                                 max_cols = 10,
                                 max_cell_chars = 80) {
  x <- as.data.frame(x, stringsAsFactors = FALSE, check.names = FALSE)
  original_rows <- nrow(x)
  original_cols <- ncol(x)
  omitted_rows <- 0L
  omitted_cols <- character()

  if (is.finite(max_cols) && original_cols > max_cols) {
    omitted_cols <- names(x)[seq.int(max_cols + 1L, original_cols)]
    x <- x[, seq_len(max_cols), drop = FALSE]
  }
  if (is.finite(max_rows) && original_rows > max_rows) {
    omitted_rows <- original_rows - max_rows
    x <- utils::head(x, max_rows)
  }

  for (name in names(x)) {
    if (is.character(x[[name]]) || is.factor(x[[name]])) {
      values <- as.character(x[[name]])
      long <- nchar(values, type = "width", allowNA = FALSE) > max_cell_chars
      values[long] <- paste0(substr(values[long], 1L, max_cell_chars - 1L), "...")
      x[[name]] <- values
    }
  }

  list(
    data = x,
    original_rows = original_rows,
    original_cols = original_cols,
    omitted_rows = omitted_rows,
    omitted_cols = omitted_cols
  )
}

emit_todo <- function(text, title = "TODO") {
  text <- trimws(render_report_text(text %||% "Add the assessment material here."))
  if (!nzchar(text)) {
    text <- "Add the assessment material here."
  }
  title <- trimws(as.character(title %||% "TODO"))
  if (!nzchar(title)) {
    title <- "TODO"
  }
  cat("::: {.callout-important appearance=\"simple\" icon=false}\n")
  cat("## ", title, "\n\n", sep = "")
  cat(text, "\n")
  cat(":::\n\n")
}

emit_config_todo <- function(field, guidance) {
  emit_todo(
    sprintf("Set `%s` in `report-config.yml`: %s", field, guidance),
    title = sprintf("CONFIG TODO: %s", field)
  )
}

configured_metadata_value <- function(name) {
  for (source_name in c("report_config", "knitr_metadata", "quarto_metadata")) {
    source <- get0(source_name, ifnotfound = list())
    value <- source[[name]]
    if (!is.null(value) && length(value) > 0 && !is.na(value[[1]]) && nzchar(as.character(value[[1]]))) {
      return(as.character(value[[1]]))
    }
  }
  ""
}

metadata_missing <- function(x, field = "") {
  x <- as.character(x %||% "")
  value <- trimws(x)
  if (!nzchar(value)) {
    return(TRUE)
  }
  if (grepl("TODO|TBD|FIXME|CHANGE[ -]?ME|REPLACE", value, ignore.case = TRUE)) {
    return(TRUE)
  }
  placeholders <- list(
    title = c("tuna assessment report template"),
    species_code = c("tuna", "species", "species_code"),
    species_label = c("selected tuna stock", "selected stock", "tuna stock"),
    species_scientific = c("thunnus spp.", "thunnus spp"),
    assessment_year = c("yyyy", "year"),
    assessment_area = c("the wcpo"),
    previous_assessment_year = c("the previous assessment"),
    model_region_count = c("number of model regions"),
    latest_data_year = c("latest data year"),
    recent_period = c("recent period"),
    no_fishing_reference_period = c("reference period")
  )
  choices <- placeholders[[field]]
  length(choices) > 0 && tolower(value) %in% choices
}

emit_config_warnings <- function() {
  checks <- list(
    title = "report title",
    species_code = "short species code used in file names and captions",
    species_label = "common species name used in report text and captions",
    species_scientific = "scientific name used in the introduction",
    assessment_year = "assessment year",
    assessment_area = "assessment area",
    previous_assessment_year = "previous assessment year for comparisons",
    model_region_count = "number of model regions",
    latest_data_year = "latest data year in the accepted input files",
    recent_period = "recent period used for stock-status summaries",
    no_fishing_reference_period = "reference period for SB[F=0] calculations"
  )
  values <- stats::setNames(lapply(names(checks), configured_metadata_value), names(checks))
  missing <- names(checks)[vapply(names(checks), function(field) {
    metadata_missing(values[[field]], field)
  }, logical(1))]
  if (!length(missing)) {
    return(invisible(FALSE))
  }
  for (field in missing) {
    emit_config_todo(field, checks[[field]])
  }
  invisible(TRUE)
}

emit_catalog_figures <- function(catalog,
                                 roots = c("Figures"),
                                 curation = data.frame(),
                                 placements = "main",
                                 empty_todo = TRUE) {
  catalog <- apply_figure_curation(catalog, curation)
  catalog <- filter_catalog_figures(catalog, placements = placements)
  if (!nrow(catalog)) {
    if (isTRUE(empty_todo)) {
      emit_todo("Add figure catalog rows to catalog/figures.csv.")
    }
    return(invisible(FALSE))
  }

  catalog <- complete_catalog(catalog, "figures")
  metadata <- read_figure_metadata(roots)

  last_section <- ""
  for (i in seq_len(nrow(catalog))) {
    section <- render_report_text(catalog$section[[i]])
    title <- render_report_text(catalog$title[[i]])
    key <- slug_id(catalog$key[[i]])
    caption <- render_report_text(catalog$caption[[i]])
    caption_override <- render_report_text(catalog$caption_override[[i]])
    todo <- render_report_text(catalog$todo[[i]])
    files <- find_report_assets(catalog$file_candidates[[i]], roots = roots)

    if (!identical(section, last_section) && nzchar(section)) {
      cat("\n## ", section, "\n\n", sep = "")
      last_section <- section
    }

    cat("### ", title, "\n\n", sep = "")
    if (length(files)) {
      for (j in seq_along(files)) {
        display_file <- preferred_figure_file(files[[j]])
        figure_id <- if (length(files) == 1L) key else paste(key, j, sep = "-")
        figure_caption <- if (length(files) == 1L) {
          figure_caption(files[[j]], caption, metadata, override = caption_override)
        } else {
          figure_caption(files[[j]], sprintf("%s (panel %d of %d).", caption, j, length(files)), metadata, override = caption_override)
        }
        cat(sprintf("![%s](%s){#fig-%s fig-align=\"center\" width=100%%}\n\n",
                    figure_caption, markdown_path(display_file), figure_id))
      }
    } else {
      emit_todo(todo)
    }
  }

  invisible(TRUE)
}

is_fishery_composition_figure <- function(path) {
  stem <- tools::file_path_sans_ext(tolower(basename(path)))
  stem <- gsub("_", "-", stem, fixed = TRUE)
  grepl("^(length|weight)-frequency(-residuals)?-fishery-", stem)
}

is_default_excluded_figure <- function(path) {
  stem <- tools::file_path_sans_ext(tolower(basename(path)))
  stem <- gsub("_", "-", stem, fixed = TRUE)
  stem %in% c(
    "hessian-diagnostics",
    "tag-recapture-pressure-release-group",
    "tag-recapture-pressure-release-group-by-fishery"
  )
}

catalog_all_candidate_tokens <- function(catalog) {
  if (!is.data.frame(catalog) || !nrow(catalog) || !"file_candidates" %in% names(catalog)) {
    return(character())
  }
  unique(unlist(lapply(catalog$file_candidates, catalog_candidate_tokens), use.names = FALSE))
}

emit_generated_figure_group <- function(files, heading, metadata, id_prefix) {
  if (!length(files)) {
    return(invisible(FALSE))
  }
  cat("\n## ", heading, "\n\n", sep = "")
  for (file in files) {
    label <- tools::file_path_sans_ext(basename(file))
    row <- figure_metadata_row(file, metadata)
    title <- if (!is.null(row) && "label" %in% names(row) && nzchar(trimws(row$label[[1]]))) {
      render_report_text(row$label[[1]])
    } else {
      title <- gsub("[-_]+", " ", label)
      paste0(toupper(substr(title, 1, 1)), substr(title, 2, nchar(title)))
    }
    cat("### ", title, "\n\n", sep = "")
    caption <- figure_caption(file, title, metadata)
    display_file <- preferred_figure_file(file)
    cat(sprintf("![%s](%s){#fig-%s-%s fig-align=\"center\" width=100%%}\n\n",
                caption, markdown_path(display_file), id_prefix, slug_id(label)))
  }
  invisible(TRUE)
}

emit_curated_file_figures <- function(curation,
                                      catalog = data.frame(),
                                      roots = c("Figures"),
                                      placements = "main",
                                      default_section = "Curated generated figures",
                                      id_prefix = "curated") {
  curation <- complete_figure_curation(curation)
  if (!nrow(curation)) {
    return(invisible(FALSE))
  }
  wanted <- vapply(placements, normalize_figure_placement, character(1), default = "main")
  placement <- vapply(curation$placement, normalize_figure_placement, character(1), default = "appendix")
  target_type <- figure_curation_target_type(curation$target_type)
  curation <- curation[target_type == "file" & placement %in% wanted, , drop = FALSE]
  if (!nrow(curation)) {
    return(invisible(FALSE))
  }

  catalog_tokens <- catalog_all_candidate_tokens(catalog)
  target_tokens <- vapply(curation$target, function(target) {
    paste(file_match_tokens(target), collapse = "\n")
  }, character(1))
  curation <- curation[!vapply(target_tokens, function(tokens) {
    any(strsplit(tokens, "\n", fixed = TRUE)[[1]] %in% catalog_tokens)
  }, logical(1)), , drop = FALSE]
  if (!nrow(curation)) {
    return(invisible(FALSE))
  }

  order_value <- suppressWarnings(as.numeric(clean_text(curation$order)))
  curation$.original_order <- seq_len(nrow(curation))
  curation$.curation_order <- order_value
  if (any(is.finite(curation$.curation_order))) {
    curation <- curation[order(is.na(curation$.curation_order), curation$.curation_order, curation$.original_order), , drop = FALSE]
  }
  curation$.original_order <- NULL
  curation$.curation_order <- NULL

  metadata <- read_figure_metadata(roots)
  last_section <- ""
  wrote <- FALSE
  for (i in seq_len(nrow(curation))) {
    target <- clean_text(curation$target[[i]])
    file <- find_report_asset(target, roots = roots)
    if (!nzchar(file) || is_default_excluded_figure(file)) {
      next
    }
    section <- render_report_text(curation$section[[i]])
    if (!nzchar(section)) {
      section <- default_section
    }
    title <- render_report_text(curation$title[[i]])
    if (!nzchar(title)) {
      title <- gsub("[-_]+", " ", tools::file_path_sans_ext(basename(file)))
      title <- paste0(toupper(substr(title, 1, 1)), substr(title, 2, nchar(title)))
    }
    if (!identical(section, last_section)) {
      cat("\n## ", section, "\n\n", sep = "")
      last_section <- section
    }
    cat("### ", title, "\n\n", sep = "")
    caption <- figure_caption(file, title, metadata, override = curation$caption_override[[i]])
    display_file <- preferred_figure_file(file)
    cat(sprintf("![%s](%s){#fig-%s-%s fig-align=\"center\" width=100%%}\n\n",
                caption, markdown_path(display_file), id_prefix, slug_id(tools::file_path_sans_ext(basename(file)))))
    wrote <- TRUE
  }
  invisible(wrote)
}

emit_extra_generated_figures <- function(catalog,
                                         roots = c("Figures"),
                                         curation = data.frame()) {
  roots <- roots[dir.exists(roots)]
  files <- sort(unique(unlist(lapply(roots, function(root) {
    list.files(root, pattern = "[.](png|jpg|jpeg|pdf|svg)$", recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
  }), use.names = FALSE)))
  files <- files[!is_optimized_sidecar_figure(files)]
  if (!length(files)) {
    return(invisible(FALSE))
  }

  catalog_candidates <- unique(unlist(strsplit(paste(catalog$file_candidates, collapse = ";"), ";", fixed = TRUE), use.names = FALSE))
  catalog_candidates <- trimws(tolower(basename(catalog_candidates)))
  catalog_stems <- tools::file_path_sans_ext(catalog_candidates)
  file_stems <- tools::file_path_sans_ext(tolower(basename(files)))
  extra <- sort(files[!file_stems %in% catalog_stems])
  extra <- extra[!is_default_excluded_figure(extra)]
  curation <- complete_figure_curation(curation)
  if (nrow(curation)) {
    extra <- extra[!vapply(extra, function(file) nrow(figure_curation_matches_file(curation, file)) > 0, logical(1))]
  }
  if (!length(extra)) {
    return(invisible(FALSE))
  }
  metadata <- read_figure_metadata(roots)

  fishery_composition <- is_fishery_composition_figure(extra)
  other_extra <- extra[!fishery_composition]
  fishery_extra <- extra[fishery_composition]

  cat("\n# Appendix: Supplemental Generated Figures\n\n")
  emit_generated_figure_group(other_extra, "Additional diagnostics", metadata, "extra")
  emit_generated_figure_group(fishery_extra, "Fishery-level composition fits", metadata, "fishery-composition")

  invisible(TRUE)
}

emit_kable <- function(x,
                       caption = NULL,
                       max_rows = 30,
                       max_cols = 8,
                       max_cell_chars = 64) {
  if (!nrow(x)) {
    return(invisible(FALSE))
  }
  table <- prepare_report_table(
    x,
    max_rows = max_rows,
    max_cols = max_cols,
    max_cell_chars = max_cell_chars
  )
  note <- character()
  if (table$omitted_rows > 0L) {
    note <- c(note, sprintf("%d rows omitted from the displayed preview.", table$omitted_rows))
  }
  if (length(table$omitted_cols)) {
    note <- c(note, sprintf("%d columns omitted: %s.", length(table$omitted_cols), paste(table$omitted_cols, collapse = ", ")))
  }
  if (length(note)) {
    cat("*Note: ", paste(note, collapse = " "), "*\n\n", sep = "")
  }
  if (requireNamespace("knitr", quietly = TRUE)) {
    format <- if (knitr::is_latex_output()) "latex" else "html"
    output <- knitr::kable(
      table$data,
      format = format,
      caption = render_report_text(caption),
      label = NA,
      booktabs = identical(format, "latex"),
      longtable = identical(format, "latex"),
      escape = TRUE
    )
    if (requireNamespace("kableExtra", quietly = TRUE)) {
      if (identical(format, "latex")) {
        output <- kableExtra::kable_styling(
          output,
          latex_options = c("repeat_header", "scale_down"),
          font_size = 8
        )
      } else {
        output <- kableExtra::kable_styling(
          output,
          full_width = FALSE,
          bootstrap_options = c("striped", "condensed", "responsive")
        )
      }
    }
    print(output)
  } else {
    cat("\n")
    print(table$data)
    cat("\n")
  }
  invisible(TRUE)
}

emit_catalog_tables <- function(catalog,
                                roots = c("tables"),
                                curation = data.frame(),
                                placements = "main",
                                empty_todo = TRUE) {
  catalog <- apply_table_curation(catalog, curation)
  catalog <- filter_catalog_tables(catalog, placements = placements)
  if (!nrow(catalog)) {
    if (isTRUE(empty_todo)) {
      emit_todo("Add table catalog rows to catalog/tables.csv.")
    }
    return(invisible(FALSE))
  }

  catalog <- complete_catalog(catalog, "tables")
  metadata <- read_table_metadata(roots)

  last_section <- ""
  for (i in seq_len(nrow(catalog))) {
    section <- render_report_text(catalog$section[[i]])
    title <- render_report_text(catalog$title[[i]])
    caption <- render_report_text(catalog$caption[[i]])
    caption_override <- render_report_text(catalog$caption_override[[i]])
    todo <- render_report_text(catalog$todo[[i]])
    file <- find_report_asset(catalog$file_candidates[[i]], roots = roots)

    if (!identical(section, last_section) && nzchar(section)) {
      cat("\n## ", section, "\n\n", sep = "")
      last_section <- section
    }

    cat("### ", title, "\n\n", sep = "")
    if (nzchar(file)) {
      data <- read_report_csv(file)
      if (nrow(data)) {
        emit_kable(data, caption = table_caption(file, caption, metadata, override = caption_override))
        cat("\n\n")
      } else {
        emit_todo(paste("Table file exists but has no rows:", file))
      }
    } else {
      emit_todo(todo)
    }
  }

  invisible(TRUE)
}

emit_curated_file_tables <- function(curation,
                                     catalog = data.frame(),
                                     roots = c("tables"),
                                     placements = "main",
                                     default_section = "Curated generated tables") {
  curation <- complete_table_curation(curation)
  if (!nrow(curation)) {
    return(invisible(FALSE))
  }
  wanted <- vapply(placements, normalize_figure_placement, character(1), default = "main")
  placement <- vapply(curation$placement, normalize_figure_placement, character(1), default = "appendix")
  target_type <- table_curation_target_type(curation$target_type)
  curation <- curation[target_type == "file" & placement %in% wanted, , drop = FALSE]
  if (!nrow(curation)) {
    return(invisible(FALSE))
  }

  catalog_tokens <- catalog_all_candidate_tokens(catalog)
  target_tokens <- vapply(curation$target, function(target) {
    paste(file_match_tokens(target), collapse = "\n")
  }, character(1))
  curation <- curation[!vapply(target_tokens, function(tokens) {
    any(strsplit(tokens, "\n", fixed = TRUE)[[1]] %in% catalog_tokens)
  }, logical(1)), , drop = FALSE]
  if (!nrow(curation)) {
    return(invisible(FALSE))
  }

  order_value <- suppressWarnings(as.numeric(clean_text(curation$order)))
  curation$.original_order <- seq_len(nrow(curation))
  curation$.curation_order <- order_value
  if (any(is.finite(curation$.curation_order))) {
    curation <- curation[order(is.na(curation$.curation_order), curation$.curation_order, curation$.original_order), , drop = FALSE]
  }
  curation$.original_order <- NULL
  curation$.curation_order <- NULL

  metadata <- read_table_metadata(roots)
  last_section <- ""
  wrote <- FALSE
  for (i in seq_len(nrow(curation))) {
    target <- clean_text(curation$target[[i]])
    file <- find_report_asset(target, roots = roots)
    if (!nzchar(file) || is_internal_report_table(file)) {
      next
    }
    section <- render_report_text(curation$section[[i]])
    if (!nzchar(section)) {
      section <- default_section
    }
    title <- render_report_text(curation$title[[i]])
    if (!nzchar(title)) {
      title <- gsub("[-_]+", " ", tools::file_path_sans_ext(basename(file)))
      title <- paste0(toupper(substr(title, 1, 1)), substr(title, 2, nchar(title)))
    }
    if (!identical(section, last_section)) {
      cat("\n## ", section, "\n\n", sep = "")
      last_section <- section
    }
    cat("### ", title, "\n\n", sep = "")
    data <- read_report_csv(file)
    if (nrow(data)) {
      emit_kable(data, caption = table_caption(file, title, metadata, override = curation$caption_override[[i]]))
      cat("\n\n")
    } else {
      emit_todo(paste("Table file exists but has no rows:", file))
    }
    wrote <- TRUE
  }
  invisible(wrote)
}

emit_extra_generated_tables <- function(catalog,
                                        roots = c("tables"),
                                        curation = data.frame()) {
  roots <- roots[dir.exists(roots)]
  files <- as.character(unique(unlist(lapply(roots, function(root) {
    list.files(root, pattern = "[.]csv$", recursive = TRUE, full.names = TRUE, ignore.case = TRUE)
  }), use.names = FALSE)) %||% character())
  files <- files[!grepl("(^|/)(mfclshiny-)?table-index[.]csv$|(^|/)generated-table-index[.]csv$", files, ignore.case = TRUE)]
  files <- files[!is_internal_report_table(files)]
  if (!length(files)) {
    return(invisible(FALSE))
  }

  catalog_candidates <- unique(unlist(strsplit(paste(catalog$file_candidates, collapse = ";"), ";", fixed = TRUE), use.names = FALSE))
  catalog_candidates <- trimws(tolower(basename(catalog_candidates)))
  catalog_stems <- tools::file_path_sans_ext(catalog_candidates)
  file_stems <- tools::file_path_sans_ext(tolower(basename(files)))
  extra <- files[!file_stems %in% catalog_stems]
  curation <- complete_table_curation(curation)
  if (nrow(curation)) {
    extra <- extra[!vapply(extra, function(file) nrow(table_curation_matches_file(curation, file)) > 0, logical(1))]
  }
  if (!length(extra)) {
    return(invisible(FALSE))
  }
  metadata <- read_table_metadata(roots)

  cat("\n# Appendix: Supplemental Generated Tables\n\n")
  for (file in extra) {
    label <- tools::file_path_sans_ext(basename(file))
    title <- gsub("[-_]+", " ", label)
    title <- paste0(toupper(substr(title, 1, 1)), substr(title, 2, nchar(title)))
    cat("### ", title, "\n\n", sep = "")
    data <- read_report_csv(file)
    if (nrow(data)) {
      emit_kable(data, caption = table_caption(file, paste("Additional generated table:", title), metadata))
      cat("\n\n")
    } else {
      emit_todo(paste("Table file exists but has no rows:", file))
    }
  }

  invisible(TRUE)
}
