Model runs
==========

Developments from the last assessment {#sec-stepwise}
-------------------------------------

The progression of the model development (referred to as the "stepwise") from the 2023 diagnostic model to the 2026 diagnostic model is described here.

### Stepwise model development

The major changes incorporated at each step in the diagnostic model development are summarised below, including the model number codes for each step, and a brief description. Each step builds from the previous step, and retains the previous changes.

1.  **\[01\]** 2023 diagnostic-model refit: Provide a reproducible reference of the previous diagnostic model for subsequent comparisons.

2.  **\[02\]** New MFCL executable updated from archived 2.2.2.0 (2023 assessment) to the recent 2.2.7.9 version used in this assessment, plus new format INI 1007: Isolates the new executable effect

3.  **\[03\]** Lorenzen natural-mortality scaling fixed to the 2023 diagnostic-model estimate: Improve model stability, recommended at the PAW.

4.  **\[04\]** Bias-corrected length-weight parameters: Update the biomass conversion for the 2026 assessment.

5.  **\[05\]** Convert to 5-region, 33-fishery structure (28 extraction, 5 index fisheries ): Represents revised spatial and fishery definitions, supported by PAW.

6.  **\[06\]** Size-composition inputs replaced with the reweighted weight data converted to lengths for longline fisheries, data until 2021: Evaluate the conversion of weight data to lengths, and all size compositions input as length frequencies.

7.  **\[07\]** Weight converted to lengths plus observed-length compositions for longline fisheries (i.e. adds the observed length data, noting previous bigeye assessment only used weight data for longline fisheries): Evaluate the effect of using observed lengths where their catch coverage exceeded that of weight samples [@peatman_analysis_2026]

8.  **\[08\]** Update data through to 2024, except for CAAL data: Extend the temporal coverage of the assessment.

9.  **\[09\]** Remove data \<70cm for PH and ID handline fisheries, remove data \>90 cm for domestic mixed gear fisheries in ID and PH: replicate this data truncation applied in previous assessments to deal with non-representative data.

10. **\[10\]** Switch to separate sdmTMB regional CPUE indices and apply the MFCL regional scaling penalty feature based on a global sdmTMB model: Penalize relative abundance differences among model regions but allow region specific CPUE indices to have individual selectivity and catchability, strong recommendation from PAW and yellowfin assessment peer review [@punt_independent_2023; @hamer_summary_2026].

11. **\[11\]** Time-varying CPUE uncertainty: Account for temporal variation in the relative precision of the CPUE indices.

12. **\[12\]** Regional scale CPUE log-scale observation-error SDs fixed at 0.35, 0.24, 0.21, 0.24 and 0.23: Set the five regional log-scale observation-error standard deviations to values obtained by maximum-likelihood estimation and retain them in subsequent steps.

13. **\[13\]** Add the new conditional age-at-length data (weighting factor = 0.75): Use the 2023 assessment weighting as the reference treatment for the new age data (i.e. no regional reweighting of the data contributions)

14. **\[14a\]** Apply the regional CAAL data reweighting by all 5 regions (i.e. reweight observed sample sizes based on relative mean CPUE among regions from global sdmTMB model, as discussed at PAW and in [@hasegawa_new_2026]: Test region-level spatial weighting.

15. **\[14b\]** As previous but combining CAAL data from regions 3 and 4 (sub-basin CAAL reweighting by CPUE): Sub-basin reweighting of the CAAL data.

16. **\[15\]** Selectivity modifications, flexible fishery-specific selectivity plus weak F10 non-decreasing penalty.

17. **\[16\]** Apply release-group-specific tag-mixing periods with K-statistic cut-off 0.2: Assign release-group-specific mixing periods (see appendix Tables in @scutt_phillips_estimation_2026

18. **\[17\]** Tag reporting rate adjustment exclusion (MFCL tag-flag02=1)in pre-mixing window: Avoid applying poorly determined or assumed reporting rates within the pre-mixing windows close to release events, post-mixing reporting-rate activation is unchanged.

19. **\[18\]** Effort-creep adjustment added to CPUE indices: Account for gradual changes in fishing efficiency.

20. **\[19\]** Apply Dirichlet-multinomial (DM) composition weighting: Estimate length-composition overdispersion internally using eight fishery groups and an effective-sample-size upper asymptote of 25.

21. **\[20\]** Increase tau ($\tau$) from 1 to 2, a value noted in previous assessments to account for assumed overdispersion in tag recapture data using negative binomial rather than Poisson.

22. **\[21\]** Add weak non-decreasing penalty on F33 (region 5 index)

23. **\[22\]** Steepness = 0.9 (mode of ensemble distribution and more defensible for tropical tuna)

24. **Diagnostic2026**

We note that many additional models were explored in the development of the diagnostic model, these are not described in this report.

Sensitivity analyses and uncertainty ensemble {#sec-sensitivity-structural-uncertainty}
---------------------------------------------

### Sensitivities {#sec-sensitivities}

One-off sensitivity models were explored to understand the sensitivity of the diagnostic model estimations to structural, biological and data uncertainties, and to inform selection of models for the uncertainty ensemble. Each one-off sensitivity model was created by making a single change to the 2026 diagnostic model. Due to the time constraints there was limited time to explore diagnostics on all sensitivities.

We primarily focused on the key sensitivities below:

1.  Steepness: 0.65, 0.95 (diagnostic model 0.9)

2.  Tag mixing: K-statistic cut-off values of 0.1, 0.3 (diagnostic 0.2)

3.  Conditional-age-at-length data weighting: 1, 0.5 (diagnostic 0.75)

4.  Adult natural morality (M and at age 40 quarter) value: Tag based = 0.062/quarter [@ducharme-barth_natural_2026], Higher M = 0.10/quarter (diagnostic 2023: 0.078/quarter)

5.  Effort creep on longline CPUE indices: 'maximum' scenario suggested from PAW [@hoyle_effort_2024] 3% per year pre 1976, 1.5% year post 1976, (diagnostic: min 1% per year pre 1976, 0.5% year post 1976).

6.  Time period of the global CPUE to use for regional scaling penalty: full time period (diagnostic: 1965-1969)

7.  Reporting rates during mixing period: reporting rates activated in mixing period (diagnostic: reporting rates not activated)

8.  Tau - 1.2, 1.4, 1.6, 1.8 (1.0 was used in the stepwise stages up until step 19, diagnostic = 2.0)

### Uncertainty characterisation {#sec-uncertainty-ensemble}

Typically, three types of uncertainty could be incorporated into the estimates of stock status used for management advice. One involves the statistical uncertainty of the estimates produced by individual models, often referred to as 'estimation' uncertainty. The second involves 'model' uncertainty, which is the uncertainty in the structural and fixed-parameter assumptions underpinning individual models, (e.g., fixed biological parameter such as M, steepness, tag mixing etc.). The third involves data inputs, such as alternative abundance indices with effort creep, size data treatments or other data inputs. A key uncertainty in models fitting to tag recapture data is tag mixing. Implementing the release group specific mixing periods based on the tag mixing simulations, allows a more continuous treatment of this uncertainty by integrating across a range of K-statistic cut-off values. We selected a range of K-statistic cut-off scenarios from 0.05 to 0.35, to cover assumptions where by tag mixing assumptions are mostly assigned as 4 quarters (K=0.05), effectively removing most of the tag data from the likelihood, to mixing assumptions that including zero or 1 quarter mixing periods (K=0.35), retaining much of the data in the likelihood. The extremes of the range of K-statistics applied are reasonable to assume as less plausible than the in between values and a flat unweighted treatment of this uncertainty is unrealistic. How to treat this uncertainty distribution needs further discussion among technical experts. This was not discussed at the PAW and we chose the pragmatic option of a symmetrical normal distribution centered on the diagnostic K-statistic of 0.2. The relationship between these K-statistic cut-off values and the assigned mixing periods can be viewed in @scutt_phillips_estimation_2026. Finally, the sensitivity analysis showed that once $\tau$ increased beyond 1.4 the key results were insensitive, so $\tau$ above 1.4 seems somewhat redundant in further downweighting the tag data influence. However there was sensitivity between 1 and 1.4. Acknowledging that the basis for setting a $\tau$ value is not clear, other than it should be above 1, we include three values for $\tau$ in the uncertainty ensemble: 1.2, 1.3, 1.4.

The 'uncertainty ensemble' provides a distribution of plausible management quantities that captures a range of structural, biological and or data uncertainties. For this assessment we have followed the Monte Carlo ensemble approach applied in the most recent skipjack [@teears_stock_2025] and south Pacific albacore assessments [@teears_stock_2024]. The choice of uncertainties to included in the ensemble models is informed by the sensitivity analyses. For the uncertainty ensemble we include a combination of parameter distributions from which values are randomly drawn which implicitly weights those draws according to the shape of the distribution, and fixed values of alternative plausible options for other factors which are drawn at random with equal probability. 100 separate combinations of these parameters/factors are drawn and each combination forms a separate model run for the uncertainty ensemble.

The parameters and fixed factors included in the uncertainty ensemble:

1.  Steepness \[beta distribution\]

2.  Tag mixing \[range of K stat values 0.05, 0.1, 0.15. 0.2, 0.25, 0.3, 0.35 - normal distribution centred on 0.2\]

3.  M at age 40 quarters \[beta distribution\]

4.  Effort creep -- 5 x options

5.  Reporting rates during mixing period: reporting rates activated, reporting rates not activated

6.  Tau = 1.2, 1.3, 1.4

**Estimation uncertainty** The inclusion of estimation uncertainty is recommended to form the basis for overall uncertainty in the management quantities. Hessian-based estimates of the standard deviations for the key management quantities are obtained using the variance-covariance matrix of the model parameters and the Delta Method.

Estimation uncertainty is provided for the terminal management quantities: $SB_{recent}$/$SB_{F=0}$, $F_{recent}$/$F_{MSY}$, $SB_{recent}$/$SB_{MSY}$. The estimation uncertainty is combined across all 100 models in the ensemble using a parametric bootstrap similar to the approach used in the 2023 bigeye assessments [@day_stock_2023]. We generate 100 random draws from normal distributions with mean and standard deviation specified for each ensemble model, in the case of $SB_{recent}$/$SB_{F=0}$, which was estimated on the log scale, transform the random deviates to normal space by taking their exponent. The management quantities with the full uncertainty are summarised with the mean, median, and 10, 25, 75 and 90 percentiles of the 10,000 values of each management quantity.
