Data compilation {#sec-data-compilation}
================

General notes {#sec-general-notes}
-------------

Data used in the bigeye tuna stock assessment using MFCL consist of catch, effort, length & weight-frequency data for the fisheries defined in the analysis, and tag-recapture data. Conditional age-at-length data are also used directly as data in the assessment model, as was recommended by the peer review of the 2020 yellowfin tuna assessment [@punt_independent_2023]. Improvements in these data inputs are ongoing and readers should refer to the companion papers highlighted at the end of Section @sec-introduction for detailed descriptions of how the data and biological inputs were formulated as only brief overviews are provided below. A summary of the data available for the assessment is provided in [@teears_background_2026], and in Figure @fig-data-coverage-tile.

Spatial stratification {#sec-spatial-stratification}
----------------------

The geographical area considered in the assessment corresponds to the WCPO (from 50$^\circ$N to 20$^\circ$S between 120$^\circ$E and 150$^\circ$W) and oceanic waters adjacent to the east Asian coast (110$^\circ$E between 20$^\circ$N and 20$^\circ$S). The eastern boundary of the assessment excludes the WCPFC Convention area component that overlaps with the Inter American Tropical Tuna Commission (IATTC) area. The assessment area is stratified into 5 regions Figure @fig-map-5regions, which is a simplification of the 9 region stratification used in the the previous four assessments. The simplified spatial structure was motivated by a general desire to reduce the complexity following SC reviews of the 2023 assessment and discussion at PAW, particularly by removing the small region 9 that was implemented in 2014, after the bigeye assessment peer review [@ianelli_independent_2012]. This small region was included to better model the tagging data from the historical Coral Sea tagging cruises [@harley_stock_2014]. Region 9 was maintained in the previous assessments, partly because of tag-recaptures with long times at liberty that were thought to provide information on natural mortality (M) which was estimated internal to the model in the 2023 assessment. In the 2026 assessment, in an attempt to improve model stability, after discussion at the PAW it was decided to return to the approach of earlier assessments and apply M as an external parameter [@hamer_summary_2026]. Related to this change the archival tag-recapture data from the Coral Sea Tagging program combined with conventional tags from the Regional Tuna Tagging Programme (RTTP) and the Pacific Tuna Tagging Programme (PTTP) was used in an external analysis to estimate an adult M and M-at-age (using previous growth curves) Lorenzen curve [@ducharme-barth_natural_2026]. The smaller Region 8 around Papua New Guinea and the Solomon Is was used in previous assessment to better model tag-recapture data in relation to assumed tag mixing. However, this was mostly related to skipjack and yellowfin that have high numbers or tag releases in that region, there are few bigeye tag releases in this region so it was deemed unnecessary to maintain this region for bigeye. This reduced the stratification to 7 regions. The are negligible tag data to inform movement across the northern (old regions 1, 3) as southern (old regions 5, 6) regions, and no other strong justification for multiple regions to the north and south of the equatorial region, so they were each reduced to single regions, retaining some spatial fleet separation by using a fleets-as-areas approach. This resulted a 4 region stratification that was supported at the PAW, and was more consistent with the conceptual model and the objective of removing unnecessary spatial complexity[@hamer_summary_2026; @hamer_review_2023]. An alternative 5 region structure was also proposed at PAW with a separate central-east equatorial region to better accommodate the concentration of tag-recapture data in that area and to improve the level of within model region tag mixing. Ultimately based on the tag mixing modeling [@scutt_phillips_estimation_2026], the 5 region structure was chosen for the 2026 assessment Figure @fig-map-5regions. The PAW also recommended to explore a single region fleets-as-area model, excluding all tag data [@hamer_summary_2026]. This exploration is provided in a companion paper to SC22 [@hampton_investigation_2026].

Temporal stratification {#sec-temporal-stratification}
-----------------------

The time period covered by the assessment is 1952--2024 which includes all significant post-war tuna fishing in the WCPO. Within this period, data were compiled into quarters (1; Jan--Mar, 2; Apr--Jun, 3; Jul--Sep, 4; Oct--Dec). As agreed at SC12, the assessment does not include data from the most recent calendar year as this is considered incomplete at the time of formulating the assessment inputs. Recent year data are also often subject to significant revision post-SC, in particular the longline data on which this assessment greatly depends.

Definition of fisheries {#sec-fisheries-definitions}
-----------------------

MFCL requires "fisheries" to be defined that consist of relatively homogeneous fishing units. Ideally, the defined fisheries will have selectivity and catchability characteristics that do not vary greatly over time and space. For most pelagic fisheries assessments, fisheries are typically defined according to combinations of gear type, fishing method and region, and for some, also flag or fleet. The simplified spatial structure of the 2026 assessment necessarily required a revision of the fisheries definitions. This revision resulted in a reduction of the total number of defined fisheries from 41 in the 2023 assessment to 33 in the current assessment (Table @tbl-fisheries-definitions). There are two fishery types:"index fisheries", that are used for generating indices of abundance for each model region (five index fisheries, see further below), and "extraction fisheries" that account for the catches removed from the stock (28 extraction fisheries). Extraction fisheries include longline, purse seine, pole and line, handline and various miscellaneous fisheries in Indonesia/Philippines/Vietnam region. Availability of data for each fishery used in the assessment model is provided in Figure @fig-data-coverage-tile.

For the 2026 assessment the large fish handline fisheries have been separated for Indonesia and Philippines to allow separate treatment of the data from these two fisheries which have different levels of catch and size composition uncertainty. Equatorial purse seine fishing activity (i.e. region 3 and 4) was aggregated over all nationalities, but stratified by region and set type, in order to sufficiently capture the variability in fishing operations and selectivity of different purse seine set types. Set types were grouped into associated (i.e. log, FAD, whale, dolphin, and unknown set types) and unassociated (free-school) sets. Additional fisheries were defined for pole-and-line fisheries and miscellaneous fisheries (gillnets, ringnets, hook-and-line, handlines etc.) in the western equatorial area/Indonesia/Philippines/Vietnam. At least one longline index fishery was defined in each region, although in regions 2, 3, 4 extraction longline fishing was separated into distant water and offshore components to account for the apparent differences in fishing practices and selectivity for these fleets in these regions.

**Longline index fisheries**: The catch-conditioned approach allows the specification of "index fisheries" that are used to provide standardised CPUE indices of abundance. Index fisheries are akin to "survey fisheries" as described for other software such as Stock Synthesis, and may be the same fisheries as the extraction fisheries, but when used as index fisheries they do not take any catch, and must have effort data to allow modeling of CPUE. For this assessment one index fishery is defined for each model region as a composite fishery composed of longline fisheries operating under various flags in each assessment region [@teears_background_2026]. In the 2023 assessment a single sdmTMB CPUE standardisation model was conducted across the entire assessment region (i.e. global model), the quarterly predictions were then aggregated and summed by model regions to generate the region specific abundance indices [@teears_cpue_2023], that were assumed to have constant catchability and selectivity. This allowed MFCL to use the differences in relative abundance indices among model regions as information on the relative size of the vulnerable population among model regions (i.e. regional scaling). The assumption of shared catchability and selectivity is problematic and can create problems with adequately fitting the size compositions for each index fishery. The yellowfin assessment peer review recommended freeing up these assumptions of shared catchability and selectivity among CPUE abundance indices [@punt_independent_2023]. This was discussed in depth at the PAW, where it was recommended to run a global sdmTMB model using the long-term Japanese operational data, use this global model for generating regional abundance indices that are assumed to have shared catchability and selectivity, but only use these for information on relative vulnerable abundance among model regions (i.e. only for regional scaling). For the region specific abundance indices, conduct individual sdmTMB CPUE models for each model region. Separate regional CPUE models could perhaps better account for regional differences in CPUE covariate relationships, and the resultant abundance indices can have their own selectivity without assuming constant catchability among model regions [@hamer_summary_2026]. This approached was adopted and required considerable additional work in the CPUE analyses [@teears_background_2026], and also modifications/enhancement to the MFCL code to allow one set of CPUE (i.e. global model) to be used to generate a regional abundance scaling penalty, and the other set of region specific CPUE indices to provide the time series abundance indices for the model to fit to [@davies_developments_2026]. Furthermore, specification of the time period from the global indices to use to calculate the regional scale penalty is required. The PAW recommended using a time period where data coverage was most broad across the global model domain, this period was 1965-1969 [@teears_background_2026]. The MFCL code was also modified to input global CPUE time series of different start and end dates so the scaling penalty could be determined for different time periods, noting the the penalty is applied only to that time period Section @sec-catch-effort-LL.

The regular longline extraction fisheries are based on the same data set, but are disaggregated into the longline fisheries defined in Table @tbl-fisheries-definitions. The size composition data (length and weight-frequency) for the extraction fisheries is assumed to represent the actual composition of the removed fish for any space-time strata, and in the data preparation process are weighted by the catch in order to represent the fisheries extractions at the spatial (region) and temporal (quarter) resolution of the model [@peatman_analysis_2026]. However, for the index fisheries, while the same aggregation process is conducted, the size data are weighted by standardised CPUE (rather than by catch) so that the size data are more representative of the abundance of the underlying population in each region and time period. Further, because the size data for the index and extraction fisheries are effectively being used twice (but weighted differently), the likelihood weighting for the size composition is adjusted such that the original intended weight (effective sample size) in the likelihood is preserved.

Catch and effort data {#sec-catch-effort-data}
---------------------

### General characteristics

Catch and effort data were compiled according to the fisheries defined in Table @tbl-fisheries-definitions. Catches by the longline fisheries were expressed in numbers of fish, and catches for all other fisheries expressed in weight (mt). This is consistent with the form in which the catch data are recorded and reported for these fisheries. The catches are aggregated at 5$^\circ$ x 5$^\circ$ and quarterly resolution, with the aggregation process either conducted by SPC, where operational data is available to inform this, or by the particular countries following statistical procedures that are reported to the Commission. For some fisheries, notably those in region 2 - Indonesian/Philippines/Vietnam - operational information on quarterly or spatial patterns in catches is poor so the annual catches are aggregated evenly across quarters and spatial cells. This is done by SPC.

In the catch conditioned model effort is not essential but is required (at least for a recent period of time) for projection analyses involving fisheries managed under effort rather than catch controls. The effort data are necessary to derive recent estimates of catchability for running the effort based projections. In this case the main industrial purse seine fisheries operating in the tropical region (i.e., regions 3, 4) are managed under effort control. Effort data for these purse seine fisheries are defined as number of sets specified by set type (associated or unassociated), and are included for the last 12 quarters to facilitate projections. The period of 12 quarters is consistent with previous projections using catch errors models. For this assessment several other fisheries also have effort included to allow effort based projection for management purposes, these are the longline extraction fisheries, with effort measured as numbers of hooks per set, and the Japanese pole and line fisheries with effort measured in vessel fishing days.

Total annual catches by major gear categories for the WCPO are shown in Figure @fig-catch-hist-full and a regional breakdown is provided in Figure @fig-catch-hist-regional. Catches by fishery groups are provided in Figure @fig-catch-by-fishery-longline, Figure @fig-catch-by-fishery-ps and Figure @fig-catch-by-fishery-other. The spatial distribution of catches over the past ten years is provided in Figure @fig-catch-map. Discarded catches are estimated to be minor and were not included in the analysis. Catches in the northern region are highly seasonal and the annual catch has been relatively stable over much of the assessment period. Most of the catch occurs in the tropical regions (2, 3 and 4).

A number of noticeable trends in the fisheries have occurred over the model period, specifically:

-   The steady increases in total bigeye catch over most of the assessment period in the equatorial regions (regions 2, 3, 4), and steady declines since around 2010, with relatively stable/slightly increasing catches over the last 5 years.

-   The relatively stable catches of bigeye in the northern temperate region by longline vessels (regions 1).

-   The development of the equatorial purse-seine fisheries from the mid-1970s and the widespread use of FADs since the mid-1990s, allowing an expansion of the purse-seine fishery, and corresponding increases in catch of bigeye, particularly in equatorial regions.

-   Large changes in the purse seine fleet composition and increasing size and likely efficiency of the fleet.

-   The steady increase in catch for the domestic fisheries of Indonesia and the Philippines (region 2) since 1970.

-   The apparent stabilisation of catches of bigeye for most gears after the mid 2000's, and declines in overall catches since around 2010.

-   The notable increase in the handline catch reported for 2024. This is the result of changes in how ID provided their catch statistics in 2026, wherebye there was a change in how bigeye catch was allocated between the small and large fish handline fisheries. ID determined that a large portion of the ID catch that was previously reported as smaller fish handline gear (part of the 'other' category) should be allocated to the larger fish handline (see @vidal_data_2026). There is yet to be a historical adjustment, and this will be important for future assessments. The single terminal year increase in the ID large fish handline catch adds to the Philippines handline catches, it will have minor influence on the current assessment, but the historical time series needs an appropriate adjustment as a priority under the WPEA project.

### Purse seine {#sec-catch-effort-PS}

For the industrial purse seine fisheries predominantly operating in tropical regions 3, and 4, catch by species within each set type (associated or unassociated) is determined by applying estimates of species composition from observer-collected samples to total catches estimated from raised logsheet data [@hampton_annual_2016; @peatman_project_2021; @peatman_project_2023]. For the Japanese (JP) fleet for which there is greater confidence in species-based reporting, reported catch by species is used. Purse seine catch for Philippines (PH) and Indonesian (ID) domestic purse seine fisheries, predominantly operating in region 2, was derived from raised port sampling data provided by these countries. We note that the COVID-19 pandemic resulted in low observer coverage of the purse seine fleets from mid 2020 to 2022 and purse seine catch estimates are less reliable over these years.

### Longline {#sec-catch-effort-LL}

For the longline fisheries catches in number of fish by species are derived from raised logbook data or annual catch estimates provided by specific countries. Effort is in terms of hooks per set.

The index fishery CPUE time series for the 2026 assessment were derived from the operational longline dataset for the Pacific region Figure @fig-cpue-nom-maps. This dataset is an amalgamation of operational level data from the distant-water fishing nations (DWFN), United States, Australian, New Zealand and Pacific-Island countries and territories (PICTs) longline fleets operating in the Pacific basin. It represents the most complete spatiotemporal record of longline fishing activity in the Pacific, spanning from 1952 through to the present and is the result of collaborative ongoing data-sharing efforts from many countries. This data-set was first created in 2015 in support of the Pacific-wide bigeye tuna stock assessment [@mckechnie_analysis_2015], and has subsequently been used in each bigeye and yellowfin tuna assessment [@mckechnie_stock_2017; @vincent_incorporation_2018; @ducharme-barth_stock_2020; @day_stock_2023]. Since 2017 spatiotemporal approaches [@thorson_geostatistical_2015] have been used for CPUE modeling in WCPFC stock assessments [@tremblay-boyer_stock_2017; @ducharme-barth_analysis_2020; @teears_cpue_2023]. Consistent with the 2023 assessment, the CPUE modeling was conducted with sdmTMB [@anderson_sdmtmb_2022]. A detailed description of the methods for generating the spatiotemporal abundance indices is provided in @teears_background_2026. However, some aspects are worth noting here. Firstly, the global analysis used for the regional scaling penalty takes account of habitat viability by not including predictions in cells when SST is below a specified thresholds. The threshold was determined as 17°C based on the probability of positive CPUE observations being greater than 10% [@teears_background_2026]. Applying the SST thresholds prevents inflating the relative abundance in the northern and southern regions by including spatial cells that have predictions of positive abundance that are unlikely in reality. The approach was a recommendation from the PAW.

The CPUE modeling for the 2026 assessment made some key improvements over the 2023 version, largely following detailed discussion and recommendations from PAW [@hamer_summary_2026]. The 2026 analysis implemented encounter and positive component sub-models separately to allow for differences in model formulas; specifically to allow the number of hooks to be included in the encounter sub-model. The inclusion of vessel ID as a random effect to account for vessel effects was another important improvement in the analysis, and the number of samples included in the sub-sampling of longline CPUE data for region specific indices was increased. Finally effort creep (positive increase in effective effort over time) was included as an adjustment on predicted regional CPUE indices. The decision at PAW was that zero effort creep was implausible, so a range of positive effort creep is explored based on the recommendation from PAW, and no zero options are included in the assessment models. Please refer to @teears_background_2026 for a full description of the CPUE modeling for generating the global and region specific abundance indices.

### Other fisheries {#sec-catch-effort-other}

Effort data for the ID, PH, and VN surface fisheries and Japanese research longline fisheries are unavailable. However, as these fisheries are not part of the index fisheries, with the catch-conditioned approached effort data are not necessary for these extraction fisheries. Catch estimates for the ID/PH/VN fisheries are derived from various port sampling programmes dating back to the 1960s for ID and the PH, and early 2000s for VN [@williams_overview_2023; @vidal_data_2026].

Size data {#sec-size-data}
---------

Available length-frequency data for each of the fisheries were compiled into 95 x 2cm size classes from 10--12 cm to 198--200 cm. Weight data were compiled into 200 x 1 kg size classes from 0--1 kg to 199--200 kg. Most weight data were recorded as processed weights (usually recorded to the nearest kilogram). Processing methods varied between fleets requiring the application of conversion factors to convert the available processed weight data to whole weight equivalents. Details of the various processed weight to whole weight conversion factors are provided in @hamer_wcpfc_2026. Note that these conversions occur in the database prior to data extraction for stock assessments [@hamer_progress_2025]. Data were either collected onboard by fishers, through observer programs, or through port sampling, see descriptions of data sources in @hamer_progress_2025; @hamer_wcpfc_2026. Each size-frequency record in the model consisted of the actual number of bigeye tuna measured and Figure @fig-data-coverage-tile provides details of the temporal availability of length and weight-frequency data (also see @teears_background_2026). Note that a maximum effective sample size of 1,000 is implemented in MFCL when using the robust normal likelihood for size composition data. The effective sample size was further down-weighted as explained in Section @sec-sizefreq-likelihood. Summaries of the available size composition data by year and fishery are provided in @teears_background_2026 and the processed data in @peatman_analysis_2026.

An extensive process of preparatory size data processing is required to improve the reliability and representativeness of size composition data. This includes aggregating data according to the spatial model regions and fisheries, filtering out unreliable data sources and low sample sizes, and re-weighting the size frequencies to better represent the catches (extraction fisheries) and relative abundance (index fisheries). Only length data are available for purse seine, pole and line and the other miscellaneous gear fisheries in the Indonesia/Philippines/Vietnam region. For longline fisheries both weight and length data are available. For the 2026 assessment, based on recommendations from previous years [@teears_cpue_2023; @day_stock_2023] and discussions at the PAW [@hamer_summary_2026], it was decided to include weight and length data for longline fisheries due to the increasing coverage of length data in recent years and the decreasing coverage of weight data [@peatman_analysis_2026]. This involved the conversion of weight data to lengths external to the model, so that the final models ran entirely on length data, this is the fist time to apply this approach. A key principle used in constructing the size composition inputs was not to use weight and length data at the same time for a fishery, even if it was available. The decision was made to start replacing the weight data (or weight converted to length) with actual length data if and when the length data had greater coverage than the weight data. The preparation of size data across the longline, purse seine, pole and line and other domestic fisheries (Indonesia/Philippines/Vietnam), including the integration of longline length data and the associated weight-length conversion process is a significant amount of work, and is fully described in the companion paper by @peatman_analysis_2026. Preparation of size data inputs has increased substantially in recent year, with increased review and scrutiny of these data and now take up a more significant time component of data inputs preparation.

The Philippines domestic handline fishery in region 2 (Fishery 15.HL.PH.2) consistently catches the largest individuals in the WCPO. Handline fishing often takes place on mixed--gear trips with other gears such as hook-and-line targeting smaller fish. To avoid "contaminating" the length-frequency data for this fishery with fish that were mis-reported as being caught using a handline, fish smaller than 70 cm were excluded, and selectivity set to zero below 70 cm, consistent with previous assessments.

Tagging data {#sec-tag-data}
------------

Of the three main tropical tuna species, bigeye tuna has the least amount of tagging data available. Information on the bigeye tag data characteristics, the process of constructing the MFCL tagging file, and estimating tag release correction factors (tagger effects) and reporting rate priors (from tag seeding experiments) can be found in @peatman_analysis_2026-1; @peatman_analysis_2026-2; @teears_background_2026. A summary of the tagging data and maps displaying tag displacements are in @teears_background_2026. Data were available from the Regional Tuna Tagging Project (RTTP) during 1989--92 (including affiliated in-country projects in the Solomon Islands, Kiribati, Fiji and the Philippines), the ongoing Pacific Tuna Tagging Programme (PTTP) that began in 2006, see Figure @fig-tag-release-recapt and Figure @fig-tag-displacement-map. The Japanese Tagging Programme (JPTP) conducted by NRIFSF and the Ajinomoto Co. Inc, over the period 2000--2020 is also included. The new tagging data for the 2026 assessment comes from PTTP. As discussed previously historical (1995, 1999-2001) data from the Coral Sea tagging cruises by CSIRO [@evans_behaviour_2008] are no longer included.

After tagged fish are recaptured, there is often a delay before the tag is reported and the data are entered into the tagging databases. If this delay is significant then reported recapture rates for recent release events will be biased low and will impact estimates of fishing mortality and population scale in the terminal time periods of the assessment. For this reason, tag releases from the PTTP are included only up until the end of 2022. The 2023 assessment included tag data until 2019. Significant numbers of tagged bigeye have been released in recent (2020 and 2021) tagging cruises focused on bigeye and yellowfin in the central Pacific (model region 4). Recaptures from these releases are available for the 2026 assessment [@teears_background_2026]. Tags were released using standard tuna tagging equipment and techniques by trained scientists and technicians. Tags have been returned from a range of fisheries, having been recovered onboard or via processing and unloading facilities throughout the Asia-Pacific region, archival and double tagged fish are not included.

The numbers of tag releases input to the assessment model are adjusted for a number of sources of tag loss, unusable recaptures due to lack of adequately resolved recapture data, estimates of tag loss (shedding and initial mortality) due to variable skill of taggers (i.e., tagger effects), and estimates of base levels of tag shedding and tag mortality. These adjustments are described in more detail in @peatman_analysis_2026-1; @teears_background_2026. An additional issue for the bigeye assessment is that there are a considerable number of tag returns that were released within the WCPO but recaptured to the east of longitude 150$^\circ$W, outside the WCPO assessment region. The adjustment or rescaling of releases for recaptures in the EPO preserves the recovery rates of tags from individual tag groups that would otherwise be biased low given that a considerable proportion of recaptures cannot be attributed to a recapture category in the assessment. These procedures were first described in @berger_analysis_2014 and @mckechnie_construction_2016. However, the releases are not adjusted for emigration outside of the model domain to the EPO. This is an important issue that requires further consideration as to options for informing adjustments to release numbers to account for emigration to the EPO.

For incorporation into the assessment, tag releases were stratified by release region, time period of release (quarter) and the same size classes used to stratify the length-frequency data. The likelihood penalties or "priors" used for the reporting rates of the grouped tag return fisheries have been updated relative to those used in the previous assessment based on the analysis of tag seeding experiments [@peatman_analysis_2026-2]. Tag reporting rate groupings are required as not all reporting fisheries have tag seeding experiments. These reporting rate grouping decisions necessarily require some expert judgement. For this assessment we have also excluded tag release groups with 5 or less recaptures from the estimation of reporting rates, as we felt there was insufficient information to inform model estimation of the reporting rates. Tag reporting rate groupings are included in Table @tbl-tag-definitions.
